server:
  port: 9191

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
          filters:
            - name: CircuitBreaker
              args:
                name: USER-SERVICE
                fallbackuri: forward:/userServiceFallBack
        - id: TWEETPOST-SERVICE
          uri: lb://TWEETPOST-SERVICE
          predicates:
            - Path=/tweetpost/**
          filters:
            - name: CircuitBreaker
              args:
                name: TWEETPOST-SERVICE
                fallbackuri: forward:/tweetPostServiceFallBack
        - id: FANOUT-SERVICE
          uri: lb://FANOUT-SERVICE
          predicates:
            - Path=/fanout/**
          filters:
            - name: CircuitBreaker
              args:
                name: FANOUT-SERVICE
                fallbackuri: forward:/fanoutServiceFallBack
        - id: MANAGETWEET-SERVICE
          uri: lb://MANAGETWEET-SERVICE
          predicates:
            - Path=/managetweet/**
          filters:
            - name: CircuitBreaker
              args:
                name: MANAGETWEET-SERVICE
                fallbackuri: forward:/managetweetServiceFallBack
        - id: PREFERENCES-SERVICE
          uri: lb://PREFERENCES-SERVICE
          predicates:
            - Path=/preferences/**
          filters:
            - name: CircuitBreaker
              args:
                name: PREFERENCES-SERVICE
                fallbackuri: forward:/preferencesServiceFallBack
        - id: SHARING-SERVICE
          uri: lb://SHARING-SERVICE
          predicates:
            - Path=/share/**
          filters:
            - name: CircuitBreaker
              args:
                name: SHARING-SERVICE
                fallbackuri: forward:/sharingServiceFallBack



hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000


management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

